// ItemIds.h
#pragma once
#include <cstdint>
#include <vector>

namespace ItemIds
{
    enum : uint16_t
    {
        // Resources
        wood = 1,
        stone,
        gold,
        diamond,
        amethyst,
        reidite,
        emerald,
        ground,
        sand,
        iceCube,
        greenGem,
        orangeGem,
        blueGem,
        demonicRune,
        demonicShard,
        satanRune,
        satanShard,
        whiteWolfFur,
        blackWolfFur,
        boarFur,
        rabbitFur,
        thread,
        scales,
        krakenSkin,
        // food
        water_bottle,
        berries,
        wheat,
        flour,
        bread,
        sandwich,
        cookies,
        rawMeat,
        cookedMeat,
        dead_fish,
        raw_fish,
        cookedFish,
        pumpkin,
        carrot,
        tomato,
        garlic,
        watermelon,
        cactus,
        aloeVera,
        // seeds
        aloeVeraSeeds,
        berrySeeds,
        wheatSeeds,
        pumpkinSeeds,
        carrotSeeds,
        tomatoSeeds,
        garlicSeeds,
        watermelonSeeds,

        // Tools
        book,
        pitchfork,
        goldPitchfork,
        wateringCan,
        filledWateringCan,
        bucket,
        wrench,
        machete,
        woodenPickaxe,
        stonePickaxe,
        stoneHammer,
        stoneShovel,
        goldPickaxe,
        goldHammer,
        goldShovel,
        diamondPickaxe,
        diamondHammer,
        diamondShovel,
        amethystPickaxe,
        amethystHammer,
        amethystShovel,
        reiditePickaxe,
        reiditeHammer,
        reiditeShovel,
        superHammer,

        // Weapons
        stoneSword,
        stoneSpear,
        stoneAxe,
        goldSword,
        goldSpear,
        goldAxe,
        diamondSword,
        diamondSpear,
        diamondAxe,
        amethystSword,
        amethystSpear,
        amethystAxe,
        reiditeSword,
        reiditeSpear,
        reiditeAxe,
        demonicSword,
        demonicSpear,
        demonicAxe,
        satanSword,
        satanSpear,
        satanAxe,
        pirateSword,

        // Clothing
        stoneHelmet,
        goldHelmet,
        diamondHelmet,
        amethystHelmet,
        reiditeHelmet,
        demonicHelmet,
        satanHelmet,
        amethystProtection,
        reiditeProtection,
        emeraldProtection,
        crownOfLife,
        crownOfLuck,
        crownOfAngel,
        divingMask,
        divingSuit,

        earmuffs,
        chapka,
        capAndScarf,
        furHat,
        hood,
        peasantsTunic,
        winterHood,
        winterPeasantsTunic,
        explorersHat,
        ninjaOutfit,
        pilot_hat,

        // Structures
        woodenWall,
        woodenDoor,
        woodenSpike,
        stoneWall,
        stoneDoor,
        stoneSpike,
        goldWall,
        goldDoor,
        goldSpike,
        diamondWall,
        diamondDoor,
        diamondSpike,
        amethystWall,
        amethystDoor,
        amethystSpike,
        reiditeWall,
        reiditeDoor,
        reiditeSpike,

        campfire,
        bigFire,
        furnace,
        workbench,
        chest,
        well,
        resurrectionStone,
        emeraldMachine,
        bridge,
        roof,
        bed,
        tower,
        plantPlot,
        windmill,
        breadOven,

        // Misc
        paper,
        bottle,
        lock,
        key,
        bandage,

        COUNT // total number of items, useful for arrays/validation
    };
}

std::vector<int> helmets = {
    ItemIds::stoneHelmet,
    ItemIds::goldHelmet,
    ItemIds::diamondHelmet,
    ItemIds::amethystHelmet,
    ItemIds::reiditeHelmet,
    ItemIds::demonicHelmet,
    ItemIds::satanHelmet,

    ItemIds::divingMask,
    ItemIds::divingSuit,

    ItemIds::earmuffs,
    ItemIds::chapka,
    ItemIds::capAndScarf,
    ItemIds::furHat,

    ItemIds::crownOfLuck,
    ItemIds::crownOfLife,
    ItemIds::crownOfAngel,

    ItemIds::hood,
    ItemIds::winterHood,
    ItemIds::peasantsTunic,
    ItemIds::winterPeasantsTunic,

    ItemIds::amethystProtection,
    ItemIds::reiditeProtection,
    ItemIds::emeraldProtection,

    ItemIds::pilot_hat,
    ItemIds::ninjaOutfit,

    ItemIds::explorersHat,
};

std::vector<int> tools = {

    ItemIds::woodenPickaxe,
    ItemIds::stonePickaxe,
    ItemIds::goldPickaxe,
    ItemIds::diamondPickaxe,
    ItemIds::amethystPickaxe,
    ItemIds::reiditePickaxe,

    ItemIds::stoneAxe,
    ItemIds::goldAxe,
    ItemIds::diamondAxe,
    ItemIds::amethystAxe,
    ItemIds::reiditeAxe,
    ItemIds::demonicAxe,
    ItemIds::satanAxe,

    ItemIds::stoneSword,
    ItemIds::goldSword,
    ItemIds::diamondSword,
    ItemIds::amethystSword,
    ItemIds::reiditeSword,
    ItemIds::demonicSword,
    ItemIds::satanSword,
    ItemIds::pirateSword,

    ItemIds::stoneSpear,
    ItemIds::goldSpear,
    ItemIds::diamondSpear,
    ItemIds::amethystSpear,
    ItemIds::reiditeSpear,
    ItemIds::demonicSpear,
    ItemIds::satanSpear,

    ItemIds::stoneHammer,
    ItemIds::goldHammer,
    ItemIds::diamondHammer,
    ItemIds::amethystHammer,
    ItemIds::reiditeHammer,
    ItemIds::superHammer,

    ItemIds::stoneShovel,
    ItemIds::goldShovel,
    ItemIds::diamondShovel,
    ItemIds::amethystShovel,
    ItemIds::reiditeShovel,

    ItemIds::goldPitchfork,
    ItemIds::pitchfork,
    ItemIds::book,
    ItemIds::wateringCan,
    ItemIds::filledWateringCan,
    ItemIds::wrench,
    ItemIds::machete,

};

std::vector<int> pickaxes = {
    0,
    ItemIds::woodenPickaxe,
    ItemIds::stonePickaxe,
    ItemIds::goldPickaxe,
    ItemIds::diamondPickaxe,
    ItemIds::amethystPickaxe,
    ItemIds::reiditePickaxe,
};

std::vector<int> consumables = {
    ItemIds::raw_fish,
    ItemIds::cookedFish,
    ItemIds::rawMeat,
    ItemIds::cookedMeat,
    
    ItemIds::berries,
    ItemIds::pumpkin,
    ItemIds::carrot,
    ItemIds::tomato,
    ItemIds::garlic,
    ItemIds::watermelon,
    ItemIds::cactus,
    ItemIds::aloeVera,
    
    ItemIds::bread,
    ItemIds::sandwich,
    ItemIds::cookies,
    
    ItemIds::bandage,
    ItemIds::water_bottle,
    // ItemIds::banana,
    // ItemIds::cake,
};

std::vector<int> weapons = {
    ItemIds::stoneSword,
    ItemIds::goldSword,
    ItemIds::diamondSword,
    ItemIds::amethystSword,
    ItemIds::reiditeSword,
    ItemIds::demonicSword,
    ItemIds::satanSword,

    ItemIds::stoneSpear,
    ItemIds::goldSpear,
    ItemIds::diamondSpear,
    ItemIds::amethystSpear,
    ItemIds::reiditeSpear,
    ItemIds::demonicSpear,
    ItemIds::satanSpear,

    ItemIds::stoneAxe,
    ItemIds::goldAxe,
    ItemIds::diamondAxe,
    ItemIds::amethystAxe,
    ItemIds::reiditeAxe,
    ItemIds::demonicAxe,
    ItemIds::satanAxe,
};

std::vector<int> plants = {
    ItemIds::aloeVeraSeeds,
    ItemIds::berrySeeds,
    ItemIds::wheatSeeds,
    ItemIds::pumpkinSeeds,
    ItemIds::carrotSeeds,
    ItemIds::tomatoSeeds,
    ItemIds::garlicSeeds,
    ItemIds::watermelonSeeds,
};
std::vector<int> buildings_ids = {

    ItemIds::aloeVeraSeeds,
    ItemIds::berrySeeds,
    ItemIds::wheatSeeds,
    ItemIds::pumpkinSeeds,
    ItemIds::carrotSeeds,
    ItemIds::tomatoSeeds,
    ItemIds::garlicSeeds,
    ItemIds::watermelonSeeds,

    ItemIds::woodenWall,
    ItemIds::woodenDoor,
    ItemIds::woodenSpike,
    ItemIds::stoneWall,
    ItemIds::stoneDoor,
    ItemIds::stoneSpike,
    ItemIds::goldWall,
    ItemIds::goldDoor,
    ItemIds::goldSpike,
    ItemIds::diamondWall,
    ItemIds::diamondDoor,
    ItemIds::diamondSpike,
    ItemIds::amethystWall,
    ItemIds::amethystDoor,
    ItemIds::amethystSpike,
    ItemIds::reiditeWall,
    ItemIds::reiditeDoor,
    ItemIds::reiditeSpike,

    ItemIds::campfire,
    ItemIds::bigFire,
    ItemIds::furnace,
    ItemIds::workbench,
    ItemIds::chest,
    ItemIds::well,
    ItemIds::resurrectionStone,
    ItemIds::emeraldMachine,
    ItemIds::bridge,
    ItemIds::roof,
    ItemIds::bed,
    ItemIds::tower,
    ItemIds::plantPlot,
    ItemIds::windmill,
    ItemIds::breadOven,

};

namespace ENTITY_TYPES
{
    enum : uint16_t
    {
        PLAYERS = 0,
        FIRE,
        WORKBENCH,
        SEED,
        WALL,
        SPIKE,
        BIG_FIRE,
        STONE_WALL,
        GOLD_WALL,
        DIAMOND_WALL,
        WOOD_DOOR,
        CHEST,
        STONE_SPIKE,
        GOLD_SPIKE,
        DIAMOND_SPIKE,
        STONE_DOOR,
        GOLD_DOOR,
        DIAMOND_DOOR,
        FURNACE,
        AMETHYST_WALL,
        AMETHYST_SPIKE,
        AMETHYST_DOOR,
        RESURRECTION,
        EMERALD_MACHINE,
        EXTRACTOR_MACHINE_STONE,
        EXTRACTOR_MACHINE_GOLD,
        EXTRACTOR_MACHINE_DIAMOND,
        EXTRACTOR_MACHINE_AMETHYST,
        EXTRACTOR_MACHINE_REIDITE,
        BRIDGE,
        WHEAT_SEED,
        WINDMILL,
        PLOT,
        BREAD_OVEN,
        WELL,
        PUMPKIN_SEED,
        ROOF,
        GARLIC_SEED,
        BED,
        TOMATO_SEED,
        CARROT_SEED,
        WOOD_DOOR_SPIKE,
        STONE_DOOR_SPIKE,
        GOLD_DOOR_SPIKE,
        DIAMOND_DOOR_SPIKE,
        AMETHYST_DOOR_SPIKE,
        REIDITE_DOOR_SPIKE,
        REIDITE_WALL,
        REIDITE_DOOR,
        REIDITE_SPIKE,
        WATERMELON_SEED,
        ALOE_VERA_SEED,
        WOOD_TOWER,
        // WOLF,
        // SPIDER,
        // FOX,
        // BEAR,
        // DRAGON,
        // PIRANHA,
        // KRAKEN,
        // CRAB,
        // FLAME,
        // reidite_DRAGON,
        // BOAR,
        // CRAB_BOSS,
        // BABY_DRAGON,
        // BABY_reidite,
        // HAWK,
        // VULTURE,
        // SAND_WORM,
        // BABY_MAMMOTH,
        // MAMMOTH,
        // HAWK_COLORED,
        // CROC,
        // BABY_HEN,
        // HEN,
        // BANANA,
        // RABBIT,
        // PENGUIN,
        // TREASURE_CHEST,
        // DEAD_BOX,
        // CRATE,
        FRUIT,
        BOX,
        WOLF,
        RABBIT,
        SPIDER,
        BOAR,
        HAWK,
        PIRANHA,
        KRAKEN,
        FOX,
        BEAR,
        FLAME,
        LAVA_GOLEM,
        VULTURE,
        SANDWORM,
    };
}