import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const lexend = localFont({
	src: [
		{
			path: "../public/fonts/Lexend/Lexend-Thin.ttf",
			weight: "100",
			style: "normal",
		},
		{
			path: "../public/fonts/Lexend/Lexend-ExtraLight.ttf",
			weight: "200",
			style: "normal",
		},
		{
			path: "../public/fonts/Lexend/Lexend-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "../public/fonts/Lexend/Lexend-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/Lexend/Lexend-Medium.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/Lexend/Lexend-SemiBold.ttf",
			weight: "600",
			style: "normal",
		},
		{
			path: "../public/fonts/Lexend/Lexend-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../public/fonts/Lexend/Lexend-ExtraBold.ttf",
			weight: "800",
			style: "normal",
		},
		{
			path: "../public/fonts/Lexend/Lexend-Black.ttf",
			weight: "900",
			style: "normal",
		},
	],
	variable: "--font-lexend",
	display: "swap",
	preload: true,
});

export const metadata: Metadata = {
	title: "Dires.io",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${lexend.variable} antialiased`}>{children}</body>
		</html>
	);
}
