// ─────────────────────────────────────────────
//  ITEM IDs
//  Sequential numbers used in the network protocol.
//  Never reorder — add new items only at the bottom.
// ─────────────────────────────────────────────
let _id = 1;
const id = () => _id++;

export const IDS = {
	// Resources
	wood: id(),
	stone: id(),
	gold: id(),
	diamond: id(),
	amethyst: id(),
	reidite: id(),
	emerald: id(),
	ground: id(),
	sand: id(),
	iceCube: id(),
	greenGem: id(),
	orangeGem: id(),
	blueGem: id(),
	demonicRune: id(),
	demonicShard: id(),
	satanRune: id(),
	satanShard: id(),
	whiteWolfFur: id(),
	blackWolfFur: id(),
	boarFur: id(),
	rabbitFur: id(),
	thread: id(),
	scales: id(),
	krakenSkin: id(),

	// Food
	water_bottle: id(),
	berries: id(),
	wheat: id(),
	flour: id(),
	bread: id(),
	sandwich: id(),
	cookies: id(),
	rawMeat: id(),
	cookedMeat: id(),
	dead_fish: id(),
	raw_fish: id(),
	cookedFish: id(),
	pumpkin: id(),
	carrot: id(),
	tomato: id(),
	garlic: id(),
	watermelon: id(),
	cactus: id(),
	aloeVera: id(),

	// Seeds
	aloeVeraSeeds: id(),
	berrySeeds: id(),
	wheatSeeds: id(),
	pumpkinSeeds: id(),
	carrotSeeds: id(),
	tomatoSeeds: id(),
	garlicSeeds: id(),
	watermelonSeeds: id(),

	// Tools
	book: id(),
	pitchfork: id(),
	goldPitchfork: id(),
	wateringCan: id(),
	filledWateringCan: id(),
	bucket: id(),
	wrench: id(),
	machete: id(),
	woodenPickaxe: id(),
	stonePickaxe: id(),
	stoneHammer: id(),
	stoneShovel: id(),
	goldPickaxe: id(),
	goldHammer: id(),
	goldShovel: id(),
	diamondPickaxe: id(),
	diamondHammer: id(),
	diamondShovel: id(),
	amethystPickaxe: id(),
	amethystHammer: id(),
	amethystShovel: id(),
	reiditePickaxe: id(),
	reiditeHammer: id(),
	reiditeShovel: id(),
	superHammer: id(),

	// Weapons
	stoneSword: id(),
	stoneSpear: id(),
	stoneAxe: id(),
	goldSword: id(),
	goldSpear: id(),
	goldAxe: id(),
	diamondSword: id(),
	diamondSpear: id(),
	diamondAxe: id(),
	amethystSword: id(),
	amethystSpear: id(),
	amethystAxe: id(),
	reiditeSword: id(),
	reiditeSpear: id(),
	reiditeAxe: id(),
	demonicSword: id(),
	demonicSpear: id(),
	demonicAxe: id(),
	satanSword: id(),
	satanSpear: id(),
	satanAxe: id(),
	pirateSword: id(),

	// Clothing
	stoneHelmet: id(),
	goldHelmet: id(),
	diamondHelmet: id(),
	amethystHelmet: id(),
	reiditeHelmet: id(),
	demonicHelmet: id(),
	satanHelmet: id(),
	amethystProtection: id(),
	reiditeProtection: id(),
	emeraldProtection: id(),
	crownOfLife: id(),
	crownOfLuck: id(),
	crownOfAngel: id(),
	divingMask: id(),
	divingSuit: id(),

	earmuffs: id(),
	chapka: id(),
	capAndScarf: id(),
	furHat: id(),
	hood: id(),
	peasantsTunic: id(),
	winterHood: id(),
	winterPeasantsTunic: id(),
	explorersHat: id(),
	ninjaOutfit: id(),
	pilot_hat: id(),

	// Structures
	woodenWall: id(),
	woodenDoor: id(),
	woodenSpike: id(),
	stoneWall: id(),
	stoneDoor: id(),
	stoneSpike: id(),
	goldWall: id(),
	goldDoor: id(),
	goldSpike: id(),
	diamondWall: id(),
	diamondDoor: id(),
	diamondSpike: id(),
	amethystWall: id(),
	amethystDoor: id(),
	amethystSpike: id(),
	reiditeWall: id(),
	reiditeDoor: id(),
	reiditeSpike: id(),

	campfire: id(),
	bigFire: id(),
	furnace: id(),
	workbench: id(),
	chest: id(),
	well: id(),
	resurrectionStone: id(),
	emeraldMachine: id(),
	bridge: id(),
	roof: id(),
	bed: id(),
	tower: id(),
	plantPlot: id(),
	windmill: id(),
	breadOven: id(),

	// Misc
	paper: id(),
	bottle: id(),
	lock: id(),
	key: id(),
	bandage: id(),
} as const;
export type ItemId = (typeof IDS)[keyof typeof IDS];

if (typeof window !== "undefined") {
	(window as any).IDS = IDS;
}

// ─────────────────────────────────────────────
//  SPRITE URLS
//  One flat object: item name → image path.
//  No index tricks, no off-by-one bugs.
// ─────────────────────────────────────────────
export const SPRITE_URLS: Record<keyof typeof IDS, string> = {
	// Resources
	wood: "/resources/wood.png",
	stone: "/resources/stone.png",
	gold: "/resources/gold.png",
	diamond: "/resources/diamond.png",
	amethyst: "/resources/amethyst.png",
	reidite: "/resources/reidite.png",
	emerald: "/resources/emerald.png",
	ground: "/items/dirt.png",
	sand: "/items/sand.png",
	iceCube: "/items/ice_cube.png",
	greenGem: "/items/green_gem.png",
	orangeGem: "/items/orange_gem.png",
	blueGem: "/items/blue_gem.png",
	demonicRune: "/items/demonic_rune.png",
	demonicShard: "/items/demonic_shard.png",
	satanRune: "/items/satan_rune.png",
	satanShard: "/items/satan_shard.png",
	whiteWolfFur: "/mobs/white_fur.png",
	blackWolfFur: "/mobs/wolf_fur.png",
	boarFur: "/mobs/boar_fur.png",
	rabbitFur: "/mobs/rabbit_fur.png",
	thread: "/mobs/thread.png",
	scales: "/mobs/scales.png",
	krakenSkin: "/mobs/kraken_skin.png",

	// Food
	water_bottle: "/food/water_bottle.png",
	berries: "/food/berry.png",
	wheat: "/food/wheat.png",
	flour: "/food/flour.png",
	bread: "/food/bread.png",
	sandwich: "/food/sandwich.png",
	cookies: "/food/cookie.png",
	rawMeat: "/food/raw_meat.png",
	cookedMeat: "/food/cooked_meat.png",
	dead_fish: "/food/dead_fish.png",
	raw_fish: "/food/raw_fish.png",
	cookedFish: "/food/cooked_fish.png",
	pumpkin: "/food/pumpkin.png",
	carrot: "/food/carrot.png",
	tomato: "/food/tomato.png",
	garlic: "/food/garlic.png",
	watermelon: "/food/watermelon.png",
	cactus: "/food/cactus.png",
	aloeVera: "/food/aloe_vera.png",

	// Seeds
	aloeVeraSeeds: "/food/aloe_vera_seeds.png",
	berrySeeds: "/food/berry_seeds.png",
	wheatSeeds: "/food/wheat_seeds.png",
	pumpkinSeeds: "/food/pumpkin_seeds.png",
	carrotSeeds: "/food/carrot_seeds.png",
	tomatoSeeds: "/food/tomato_seeds.png",
	garlicSeeds: "/food/garlic_seeds.png",
	watermelonSeeds: "/food/watermelon_seeds.png",

	// Tools
	woodenPickaxe: "/tools/wood_pickaxe.png",
	stoneHammer: "/tools/stone_hammer.png",
	stoneShovel: "/tools/stone_shovel.png",
	book: "/tools/book.png",
	stonePickaxe: "/tools/stone_pickaxe.png",
	pitchfork: "/tools/pitchfork.png",
	goldPickaxe: "/tools/gold_pickaxe.png",
	goldHammer: "/tools/gold_hammer.png",
	goldShovel: "/tools/gold_shovel.png",
	goldPitchfork: "/tools/gold_pitchfork.png",
	diamondPickaxe: "/tools/diamond_pickaxe.png",
	diamondHammer: "/tools/diamond_hammer.png",
	diamondShovel: "/tools/diamond_shovel.png",
	wateringCan: "/tools/watercan.png",
	filledWateringCan: "/tools/filled_watercan.png",
	amethystPickaxe: "/tools/amethyst_pickaxe.png",
	amethystHammer: "/tools/amethyst_hammer.png",
	amethystShovel: "/tools/amethyst_shovel.png",
	bucket: "/items/bucket.png",
	reiditePickaxe: "/tools/reidite_pickaxe.png",
	reiditeHammer: "/tools/reidite_hammer.png",
	reiditeShovel: "/tools/reidite_shovel.png",
	wrench: "/tools/wrench.png",
	superHammer: "/tools/emerald_hammer.png",
	machete: "/tools/machete.png",

	// Weapons
	stoneSword: "/tools/stone_sword.png",
	stoneSpear: "/tools/stone_spear.png",
	stoneAxe: "/tools/stone_axe.png",
	goldSword: "/tools/gold_sword.png",
	goldSpear: "/tools/gold_spear.png",
	goldAxe: "/tools/gold_axe.png",
	diamondSword: "/tools/diamond_sword.png",
	diamondSpear: "/tools/diamond_spear.png",
	diamondAxe: "/tools/diamond_axe.png",
	amethystSword: "/tools/amethyst_sword.png",
	amethystSpear: "/tools/amethyst_spear.png",
	amethystAxe: "/tools/amethyst_axe.png",
	reiditeSword: "/tools/reidite_sword.png",
	reiditeSpear: "/tools/reidite_spear.png",
	reiditeAxe: "/tools/reidite_axe.png",
	demonicSword: "/tools/demonic_sword.png",
	demonicSpear: "/tools/demonic_spear.png",
	demonicAxe: "/tools/demonic_axe.png",
	satanSword: "/tools/satan_sword.png",
	satanSpear: "/tools/satan_spear.png",
	satanAxe: "/tools/satan_axe.png",
	pirateSword: "/tools/pirate_sword.png",

	// Clothing
	stoneHelmet: "/hats/stone_helmet.png",
	goldHelmet: "/hats/gold_helmet.png",
	diamondHelmet: "/hats/diamond_helmet.png",
	amethystHelmet: "/hats/amethyst_helmet.png",
	reiditeHelmet: "/hats/reidite_helmet.png",
	demonicHelmet: "/hats/demonic_helmet.png",
	satanHelmet: "/hats/satan_helmet.png",
	earmuffs: "/hats/earmuffs.png",
	chapka: "/hats/chapka.png",
	capAndScarf: "/hats/scarf.png",
	furHat: "/hats/fur_hat.png",
	amethystProtection: "/hats/amethyst_protection2.png",
	reiditeProtection: "/hats/reidite_protection2.png",
	emeraldProtection: "/hats/emerald_protection.png",
	crownOfLife: "/hats/green_crown.png",
	crownOfLuck: "/hats/orange_crown.png",
	crownOfAngel: "/hats/blue_crown.png",
	divingMask: "/hats/diving_suit.png",
	divingSuit: "/hats/super_diving_suit.png",
	hood: "/hats/hood.png",
	peasantsTunic: "/hats/peasant.png",
	winterHood: "/hats/super_hood.png",
	winterPeasantsTunic: "/hats/super_peasant.png",
	explorersHat: "/hats/explorer.png",
	ninjaOutfit: "/hats/ninja.png",
	pilot_hat: "/hats/pilot.png",

	// Structures
	woodenWall: "/buildings/wood_wall.png",
	woodenDoor: "/buildings/wood_door.png",
	woodenSpike: "/buildings/wood_spike.png",
	stoneWall: "/buildings/stone_wall.png",
	stoneDoor: "/buildings/stone_door.png",
	stoneSpike: "/buildings/stone_spike.png",
	goldWall: "/buildings/gold_wall.png",
	goldDoor: "/buildings/gold_door.png",
	goldSpike: "/buildings/gold_spike.png",
	diamondWall: "/buildings/diamond_wall.png",
	diamondDoor: "/buildings/diamond_door.png",
	diamondSpike: "/buildings/diamond_spike.png",
	amethystWall: "/buildings/amethyst_wall.png",
	amethystDoor: "/buildings/amethyst_door.png",
	amethystSpike: "/buildings/amethyst_spike.png",
	reiditeWall: "/buildings/reidite_wall.png",
	reiditeDoor: "/buildings/reidite_door.png",
	reiditeSpike: "/buildings/reidite_spike.png",
	campfire: "/buildings/camp_fire.png",
	bigFire: "/buildings/big_camp_fire.png",
	furnace: "/buildings/furnace.png",
	workbench: "/buildings/workbench.png",
	chest: "/buildings/chest.png",
	well: "/buildings/well.png",
	resurrectionStone: "/buildings/resurrection_stone.png",
	emeraldMachine: "/buildings/emerald_machine.png",
	bridge: "/buildings/bridge.png",
	roof: "/buildings/roof.png",
	bed: "/buildings/bed.png",
	tower: "/buildings/tower.png",
	plantPlot: "/buildings/plot.png",
	windmill: "/buildings/windmill.png",
	breadOven: "/buildings/oven.png",

	// Misc
	paper: "/items/paper.png",
	bottle: "/items/bottle.png",
	lock: "/items/lock.png",
	key: "/items/key.png",
	bandage: "/items/bandage.png",
};

// ─────────────────────────────────────────────
//  BUILDINGS SET
//  Items that are placed in the world.
// ─────────────────────────────────────────────
export const buildings = new Set<ItemId>([
	IDS.berrySeeds,
	IDS.wheatSeeds,
	IDS.pumpkinSeeds,
	IDS.carrotSeeds,
	IDS.tomatoSeeds,
	IDS.garlicSeeds,
	IDS.watermelonSeeds,
	IDS.aloeVeraSeeds,
	IDS.woodenWall,
	IDS.woodenDoor,
	IDS.woodenSpike,
	IDS.stoneWall,
	IDS.stoneDoor,
	IDS.stoneSpike,
	IDS.goldWall,
	IDS.goldDoor,
	IDS.goldSpike,
	IDS.diamondWall,
	IDS.diamondDoor,
	IDS.diamondSpike,
	IDS.amethystWall,
	IDS.amethystDoor,
	IDS.amethystSpike,
	IDS.reiditeWall,
	IDS.reiditeDoor,
	IDS.reiditeSpike,
	IDS.campfire,
	IDS.bigFire,
	IDS.furnace,
	IDS.workbench,
	IDS.chest,
	IDS.well,
	IDS.resurrectionStone,
	IDS.emeraldMachine,
	IDS.bridge,
	IDS.roof,
	IDS.bed,
	IDS.tower,
	IDS.plantPlot,
	IDS.windmill,
	IDS.breadOven,
]);

const spriteCache = new Map<ItemId, HTMLImageElement>();

if (typeof window !== "undefined") {
	for (const [name, src] of Object.entries(SPRITE_URLS) as [keyof typeof IDS, string][]) {
		const img = new Image();
		img.src = src;
		spriteCache.set(IDS[name], img);
	}
}

export function getSprite(itemId: ItemId): HTMLImageElement | undefined {
	return spriteCache.get(itemId);
}

// ─────────────────────────────────────────────
//  WORLD / MOB SPRITES
//  These are separate spritesheets, not inventory items.
// ─────────────────────────────────────────────
export const WORLD_SPRITES = {
	cactus: "/world/bush.png",
	bush: "/world/bush.png",
	tree: "/world/tree.png",
	stone: "/world/stone.png",
	gold: "/world/gold.png",
	diamond: "/world/diamond.png",
	amethyst: "/world/amethyst.png",
	reidite: "/world/reidite.png",
	emerald: "/world/emerald.png",

	// minimap variants
	cactus_mm: "/world/bush_minimap.png",
	bush_mm: "/world/bush_minimap.png",
	tree_mm: "/world/tree_minimap.png",
	stone_mm: "/world/stone_minimap.png",
	gold_mm: "/world/gold_minimap.png",
	diamond_mm: "/world/diamond_minimap.png",
	amethyst_mm: "/world/amethyst_minimap.png",
	reidite_mm: "/world/reidite_minimap.png",
	emerald_mm: "/world/emerald_minimap.png",
	// effects
	rain_drop: "/world/raindrop.png",
	snowflake: "/world/snowflake.png",

	// Plants (unripe)
	berry: "/food/pumpkin_plant.png",
	wheat: "/food/pumpkin_plant.png",
	pumpkin: "/food/pumpkin_plant.png",
	carrot: "/food/pumpkin_plant.png",
	tomato: "/food/pumpkin_plant.png",
	garlic: "/food/pumpkin_plant.png",
	watermelon: "/food/pumpkin_plant.png",
	aloeVera: "/food/pumpkin_plant.png",

	// Plants (ripe)
	berry_grown: "/food/pumpkin_plant2.png",
	wheat_grown: "/food/pumpkin_plant2.png",
	pumpkin_grown: "/food/pumpkin_plant2.png",
	carrot_grown: "/food/pumpkin_plant2.png",
	tomato_grown: "/food/pumpkin_plant2.png",
	garlic_grown: "/food/pumpkin_plant2.png",
	watermelon_grown: "/food/pumpkin_plant2.png",
	aloeVera_grown: "/food/pumpkin_plant2.png",
} as const;

export const MOB_SPRITES = {
	wolf: "/world/wolf.png",
	rabbit: "/world/rabbit.png",
	spider: "/world/spider.png",
	box: "/skins/box1.png",
} as const;

export const MACHINE_SPRITES = {
	ovenOn: "/buildings/ovenon.png",
} as const;

// Ghost / death sprite
let ghostSprite: HTMLImageElement | null = null;
if (typeof window !== "undefined") {
	const img = new Image();
	img.src = "/skins/ghost.png";
	ghostSprite = img;
}
export { ghostSprite };

let COUNTER = 0;
export const ITEMS = {
	PLAYERS: COUNTER++,
	FIRE: COUNTER++,
	WORKBENCH: COUNTER++,
	SEED: COUNTER++,
	WALL: COUNTER++,
	SPIKE: COUNTER++,
	BIG_FIRE: COUNTER++,
	STONE_WALL: COUNTER++,
	GOLD_WALL: COUNTER++,
	DIAMOND_WALL: COUNTER++,
	WOOD_DOOR: COUNTER++,
	CHEST: COUNTER++,
	STONE_SPIKE: COUNTER++,
	GOLD_SPIKE: COUNTER++,
	DIAMOND_SPIKE: COUNTER++,
	STONE_DOOR: COUNTER++,
	GOLD_DOOR: COUNTER++,
	DIAMOND_DOOR: COUNTER++,
	FURNACE: COUNTER++,
	AMETHYST_WALL: COUNTER++,
	AMETHYST_SPIKE: COUNTER++,
	AMETHYST_DOOR: COUNTER++,
	RESURRECTION: COUNTER++,
	EMERALD_MACHINE: COUNTER++,

	EXTRACTOR_MACHINE_STONE: COUNTER++,
	EXTRACTOR_MACHINE_GOLD: COUNTER++,
	EXTRACTOR_MACHINE_DIAMOND: COUNTER++,
	EXTRACTOR_MACHINE_AMETHYST: COUNTER++,
	EXTRACTOR_MACHINE_REIDITE: COUNTER++,

	BRIDGE: COUNTER++,
	WHEAT_SEED: COUNTER++,
	WINDMILL: COUNTER++,
	PLOT: COUNTER++,
	BREAD_OVEN: COUNTER++,
	WELL: COUNTER++,
	PUMPKIN_SEED: COUNTER++,
	ROOF: COUNTER++,
	GARLIC_SEED: COUNTER++,
	BED: COUNTER++,

	TOMATO_SEED: COUNTER++,
	CARROT_SEED: COUNTER++,

	WOOD_DOOR_SPIKE: COUNTER++,
	STONE_DOOR_SPIKE: COUNTER++,
	GOLD_DOOR_SPIKE: COUNTER++,
	DIAMOND_DOOR_SPIKE: COUNTER++,
	AMETHYST_DOOR_SPIKE: COUNTER++,
	REIDITE_DOOR_SPIKE: COUNTER++,

	REIDITE_WALL: COUNTER++,
	REIDITE_DOOR: COUNTER++,
	REIDITE_SPIKE: COUNTER++,

	WATERMELON_SEED: COUNTER++,
	ALOE_VERA_SEED: COUNTER++,
	WOOD_TOWER: COUNTER++,

	// WOLF: COUNTER++,
	// SPIDER: COUNTER++,
	// FOX: COUNTER++,
	// BEAR: COUNTER++,
	// DRAGON: COUNTER++,
	// PIRANHA: COUNTER++,
	// KRAKEN: COUNTER++,
	// CRAB: COUNTER++,
	// FLAME: COUNTER++,
	// reidite_DRAGON: COUNTER++,
	// BOAR: COUNTER++,
	// CRAB_BOSS: COUNTER++,
	// BABY_DRAGON: COUNTER++,
	// BABY_reidite: COUNTER++,
	// HAWK: COUNTER++,
	// VULTURE: COUNTER++,
	// SAND_WORM: COUNTER++,
	// BABY_MAMMOTH: COUNTER++,
	// MAMMOTH: COUNTER++,

	// HAWK_COLORED: COUNTER++,
	// CROC: COUNTER++,
	// BABY_HEN: COUNTER++,
	// HEN: COUNTER++,
	// BANANA: COUNTER++,

	// RABBIT: COUNTER++,
	// PENGUIN: COUNTER++,
	// TREASURE_CHEST: COUNTER++,
	// DEAD_BOX: COUNTER++,
	// CRATE: COUNTER++,
	FRUIT: COUNTER++,
	BOX: COUNTER++,

	WOLF: COUNTER++,
	RABBIT: COUNTER++,
	SPIDER: COUNTER++,
	BOAR: COUNTER++,
	HAWK: COUNTER++,
	PIRANHA: COUNTER++,
	KRAKEN: COUNTER++,
	FOX: COUNTER++,
	BEAR: COUNTER++,
	FLAME: COUNTER++,
	LAVA_GOLEM: COUNTER++,
	VULTURE: COUNTER++,
	SANDWORM: COUNTER++,
};
